# Generated by Django 3.1.4 on 2020-12-12 18:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mcq_app', '0002_auto_20201212_1958'),
    ]

    operations = [
        migrations.RenameField(
            model_name='category',
            old_name='name',
            new_name='title',
        ),
    ]
