# Generated by Django 3.1.4 on 2020-12-16 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mcq_app', '0003_auto_20201212_2002'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='ques_num',
            field=models.CharField(max_length=2, null=True),
        ),
    ]
