# Generated by Django 3.1.4 on 2020-12-16 12:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mcq_app', '0004_auto_20201216_1430'),
    ]

    operations = [
        migrations.CreateModel(
            name='Everything',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='mcq_app.answer')),
                ('category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='mcq_app.category')),
                ('question', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='mcq_app.question')),
            ],
        ),
    ]
