# Generated by Django 3.1.4 on 2020-12-24 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mcq_app', '0005_everything'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='ques_num',
        ),
        migrations.AlterField(
            model_name='category',
            name='title',
            field=models.CharField(max_length=2, null=True),
        ),
    ]
