# Generated by Django 3.1.4 on 2020-12-24 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mcq_app', '0007_auto_20201224_1555'),
    ]

    operations = [
        migrations.AddField(
            model_name='answer',
            name='correct',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.DeleteModel(
            name='Question_Answer',
        ),
    ]
