# Generated by Django 3.1.4 on 2020-12-24 15:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mcq_app', '0008_auto_20201224_1624'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cat_Amount',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(null=True)),
                ('category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='mcq_app.category')),
            ],
        ),
    ]
