# Generated by Django 3.1.4 on 2021-01-25 04:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mcq_app', '0011_test'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='test',
            name='template',
        ),
        migrations.AddField(
            model_name='test',
            name='cat_amount',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='mcq_app.cat_amount'),
        ),
    ]
