# Generated by Django 3.1.4 on 2021-01-27 22:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mcq_app', '0013_auto_20210125_0720'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cat_amount',
            name='template',
        ),
        migrations.AddField(
            model_name='cat_amount',
            name='template',
            field=models.ManyToManyField(to='mcq_app.Template'),
        ),
    ]
